version: '3.8'

services:

  api:
    build: ./app
    ports:
      - 8004:8000
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: ./app
    command: celery --app=app.services.worker.celery worker --loglevel=info
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - redis

  redis:
    image: redis:6-alpine
